In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_list2 = [11,22,33,44]

In [5]:
my_array1 = np.array(my_list1)

In [7]:
my_lists = [my_list1, my_list2]

In [13]:
my_array2 = np.array(my_lists)

In [14]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
my_array2.shape

(2, 4)

In [16]:
my_array2.dtype

dtype('int64')

In [17]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype

dtype('float64')

In [21]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [26]:
np.empty(5, dtype="int64")

array([0, 0, 0, 0, 0])

In [27]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])