In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)

In [6]:
A

array([ 0.27781168,  0.89990148,  1.83495875,  1.30263819, -0.90147654,
        0.18634613, -0.15605826,  0.40385819,  0.70677349,  0.52327346])

In [8]:
B = np.random.randn(10)
B

array([-0.28446841, -2.05679962,  0.81316248,  0.38508063,  0.42762186,
        2.72656661,  0.0895171 , -1.46051262, -0.68263955,  1.28364378])

In [10]:
# Binary Functions
np.add(A,B)

array([-0.00665672, -1.15689814,  2.64812123,  1.68771882, -0.47385468,
        2.91291274, -0.06654116, -1.05665442,  0.02413395,  1.80691724])

In [11]:
np.maximum(A,B)

array([ 0.27781168,  0.89990148,  1.83495875,  1.30263819,  0.42762186,
        2.72656661,  0.0895171 ,  0.40385819,  0.70677349,  1.28364378])